Use CSS to set offcanvas nav direction
CityOfDetroit/COD-Design-System pull request #125
Opened 2023-11-29 21:56 UTC by maxatdetroit

## Part of #122 

## This PR

* Remove the necessity to use `flex-column` on navbar when inside offcanvas
* Use custom class `offcanvas-nav` and stylesheets to set column flex direction 

We need this change for the following reason:

For #122 we want to support an expandable navbar with nav hidden in an offcanvas element on small screens. E.g. [this demo](https://stackblitz.com/edit/gtrwoz-jghnee?file=index.html). However this is not possible when using `data-vertical` and `flex-column` because bootstrap's `flex-column` utility uses `!important` which would override any flex direction we set on responsive breakpoints.

## Testing

Confirm that vertical nav option still works when explicitly set by `data-vertical`.

https://github.com/CityOfDetroit/COD-Design-System/assets/143553259/fb720d2a-c3c2-4d46-aba4-70ef6650b248

Confirm that offcanvas navigation links are column flex direction even when `data-vertical` is not set.

https://github.com/CityOfDetroit/COD-Design-System/assets/143553259/0255fb44-1eec-4f39-a870-1e44f2dacd09

2023-12-01 16:47 UTC, jedgar1mx requested changes

2023-12-01 16:47 UTC, jedgar1mx commented on src/components/molecules/Nav/Nav.css
> +  flex-direction: column;
Remove

2023-12-01 16:47 UTC, jedgar1mx commented on src/components/atoms/OffcanvasBody/OffcanvasBody.js
> +          node.setAttribute('data-offcanvas-nav', true);
Set to
`node.setAttribute('data-extra-classes', 'navbar-nav')`

2023-12-01 16:47 UTC, jedgar1mx commented on src/components/molecules/Nav/Nav.js
> +    if (isOffcanvasNav) {
Remove

2023-12-01 23:18 UTC, maxatdetroit commented
@jedgar1mx the suggestions mostly work but the alignment is off.


https://github.com/CityOfDetroit/COD-Design-System/assets/143553259/d26f373a-17e1-4bf3-8e5d-e2cbe873751c

I'll check the styles applied and see what the issue is. Probably some padding/margin issue on the dropdown.

2023-12-04 15:56 UTC, maxatdetroit commented
Comments are resolved. Thanks for leaving those suggestions.

I also had to update the stylesheets to set a consistent padding for buttons and links in the navbar.

2023-12-05 17:53 UTC, jedgar1mx approved these changes

2023-12-05 17:53 UTC, merged