Add icons for documents projects, wikis, and discounts
CityOfDetroit/COD-Design-System pull request #157
Opened 2024-02-09 21:23 UTC by maxatdetroit

## Closes #153 

## Context

See CityOfDetroit/COD-Design-System#153.

## This PR

* Add bootstrap icons that most closely resemble the fontawesome icons used in intranet site
* Sort the list of icon options in storybook for easier use

## Test

* Chromatic to confirm this doesn't impact existing components
* Also manually used the story for Icons in storybook to confirm the icon SVGs are mapped correctly: http://localhost:6006/?path=/docs/components-atoms-icon--docs

2024-02-09 21:35 UTC, jedgar1mx requested changes

2024-02-09 21:35 UTC, jedgar1mx commented on src/components/atoms/Icon/Icon.js
> +                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-dollar" viewBox="0 0 16 16">
Need to pass `width` and `height` to the svg so it resizes.

2024-02-12 15:43 UTC, maxatdetroit commented on src/components/atoms/Icon/Icon.js
> +                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-currency-dollar" viewBox="0 0 16 16">
nice catch, will get that updated.

2024-02-12 15:47 UTC, maxatdetroit commented
@jedgar1mx fixed the sizing and tested in storybook.

2024-02-12 17:51 UTC, jedgar1mx approved these changes

2024-02-12 17:51 UTC, merged