Move Current Components to Experimental Section in Storybook
CityOfDetroit/COD-Design-System pull request #273
Opened 2024-12-21 02:14 UTC by sreidthomas

This PR introduces an Experimental section in Storybook and moves all current components and form components under this section. Additionally, it updates build configurations and scripts to reflect these changes.

### **Key Updates**
**1. Create Experimental Section in Storybook**

    Updated the title property in each story file for the components and form components to include Experimental/ as a prefix.
        For example:
            Changed "Components/Button" to "Experimental/Components/Button".
            Changed "Forms/Input" to "Experimental/Forms/Input".
    Outcome: Components now appear under the "Experimental" section in the Storybook sidebar.

**2. Update Documentation**

    Updated the documentation under the COD UXDS section to include the following details:
        Experimental Components: These components are unstable and should only be used for testing purposes. They:
            May undergo significant changes.
            Are not suitable for production environments.
            Should be used at the user's own risk.

**3. Rename Component Index**

    Renamed the main component index file:
        From: src/index.js
        To: src/index-experimental.js.
    Updated the Webpack configuration:
        Changed the entry point:
            From: ./src/index.js
            To: ./src/index-experimental.js.
        Updated the build output directory:
            From: build/
            To: build/experimental/.
    Verified functionality by running npm run build and yarn storybook.

**4. Rename Build Script**

    Updated the package.json file:
        Renamed the build script:
            From: "build": "webpack --mode production"
            To: "build:experimental": "webpack --mode production".
    Verified the build process by running yarn build:experimental.

2025-01-03 14:35 UTC, sreidthomas commented
### **Design System is working and updated:**

![image](https://github.com/user-attachments/assets/ebf343c6-a707-413a-97cc-d1c105a7cf01)

2025-01-03 15:34 UTC, maxatdetroit requested changes
Would you also move the component implementations into a separate experimental directory as well to organize the code in the repo?

Please use the `git mv` command where possible to make the PR easier to review.

The final directory structure should look like:
```
src
├── experimental
    ├── components
    ├── index-experimental.js
    └── stories
├── stable
    ├── components
    ├── index-stable.js
    └── stories
├── scss
└── shared
```

2025-01-03 15:34 UTC, maxatdetroit commented on src/stories/Introduction.stories.mdx
> +  are in development and should be considered unstable. They are provided for
This documentation will be more timeless if we remove the 'now' from the first sentence.

2025-01-03 15:51 UTC, sreidthomas commented
> Would you also move the component implementations into a separate experimental directory as well to organize the code in the repo?
> 
> Please use the `git mv` command where possible to make the PR easier to review.
> 
> The final directory structure should look like:
> 
> ```
> src
> ├── experimental
>     ├── components
>     ├── index-experimental.js
>     └── stories
> ├── stable
>     ├── components
>     ├── index-stable.js
>     └── stories
> ├── scss
> └── shared
> ```

For the stable directory, those are just empty files and folders for now right @maxatdetroit?

2025-01-03 16:34 UTC, maxatdetroit commented
@sreidthomas you can also pull the latest dev branch (with #275 included) and merge it into this branch to fix the CI errors.

2025-01-03 16:34 UTC, sreidthomas commented
> Would you also move the component implementations into a separate experimental directory as well to organize the code in the repo?
> 
> Please use the `git mv` command where possible to make the PR easier to review.
> 
> The final directory structure should look like:
> 
> ```
> src
> ├── experimental
>     ├── components
>     ├── index-experimental.js
>     └── stories
> ├── stable
>     ├── components
>     ├── index-stable.js
>     └── stories
> ├── scss
> └── shared
> ```
@maxatdetroit 
![image](https://github.com/user-attachments/assets/8400e0ba-bb8a-4b76-9237-714505b27467)

2025-01-03 17:25 UTC, maxatdetroit commented
@sreidthomas the new directory structure is causing some issues finding files during JS imports. You'll have to fix that to fix the new CI failures.

2025-01-03 17:27 UTC, maxatdetroit requested changes
Moving the component implementation files is causing import errors that need to be fixed.

2025-01-07 21:35 UTC, maxatdetroit approved these changes
Looks good, nice work!

2025-01-07 21:35 UTC, merged