Add Accordion list style option
CityOfDetroit/COD-Design-System pull request #90
Opened 2023-09-12 14:48 UTC by maxatdetroit

Context
---

We want to add options to the Accordion component and to the List Group component in order to support a list style. See CityOfDetroit/detroitmi#1086 for an example.

This PR
---
This PR:
* updates the Accordion component to support a list style by setting the data-ol attribute on the accordion component
* removes unused variables from accordion components
* updates accordion to use the canonical [`assignedElements`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/assignedElements) when listing to slot changes

There are a few other things that can be done in future PRs:
* Dynamically update list numbers to match accordion header text styles
* Use alternating colors for list numbers and border (Note: I don't believe this is actually desirable)

Test
---

Added a story for list-style accordion component. Looks good on desktop and mobile.
<img width="1255" alt="Screenshot 2023-09-12 at 10 43 57 AM" src="https://github.com/jedgar1mx/COD-Design-System/assets/143553259/495c4129-3c6e-45ad-bad2-0dc957fbc888">
<img width="371" alt="Screenshot 2023-09-12 at 10 44 10 AM" src="https://github.com/jedgar1mx/COD-Design-System/assets/143553259/4499d07b-b2aa-47a9-bb5e-09264b4af866">

Ran all rendering tests:
```
$ yarn test-storybook
 PASS   browser: chromium  src/stories/offcanvas.stories.js
 PASS   browser: chromium  src/stories/modal.stories.js
 PASS   browser: chromium  src/stories/accordion.stories.js
 PASS   browser: chromium  src/stories/listgroup.stories.js
 PASS   browser: chromium  src/stories/card.stories.js
 PASS   browser: chromium  src/stories/alert.stories.js
 PASS   browser: chromium  src/stories/dropdown.stories.js
 PASS   browser: chromium  src/stories/pagination.stories.js
 PASS   browser: chromium  src/stories/image.stories.js
 PASS   browser: chromium  src/stories/formcheck.stories.js
 PASS   browser: chromium  src/stories/geocoder.stories.js
 PASS   browser: chromium  src/stories/navbar.stories.js
 PASS   browser: chromium  src/stories/carousel.stories.js
 PASS   browser: chromium  src/stories/buttongroup.stories.js
 PASS   browser: chromium  src/stories/nav.stories.js
 PASS   browser: chromium  src/stories/container.stories.js
 PASS   browser: chromium  src/stories/badge.stories.js
 PASS   browser: chromium  src/stories/formcontrol.stories.js
 PASS   browser: chromium  src/stories/form.stories.js
 PASS   browser: chromium  src/stories/formlabel.stories.js
 PASS   browser: chromium  src/stories/progress.stories.js
 PASS   browser: chromium  src/stories/button.stories.js
 PASS   browser: chromium  src/stories/spinner.stories.js
 PASS   browser: chromium  src/stories/icon.stories.js
 PASS   browser: chromium  src/stories/formcheckgroup.stories.js
 PASS   browser: chromium  src/stories/formselect.stories.js
 PASS   browser: chromium  src/stories/range.stories.js
 PASS   browser: chromium  src/stories/breadcrumb.stories.js
 PASS   browser: chromium  src/stories/loader.stories.js
 PASS   browser: chromium  src/stories/table.stories.js (7.346 s)

Test Suites: 30 passed, 30 total
Tests:       155 passed, 155 total
Snapshots:   0 total
Time:        8.966 s
Ran all test suites.
```

2023-09-12 17:56 UTC, jedgar1mx requested changes
We need a way to manipulate the list box color outside of the default single color.. We have instances where each item has to be a different color.

2023-09-13 21:32 UTC, maxatdetroit commented
FYI - I'm struggling with line endings making it look like I changed every single line of code in the files I touched. Working on resolving that now.

2023-09-14 13:00 UTC, maxatdetroit commented
@jedgar1mx this should be good for another review. 

See the original comment for an update on what it looks like with customizable colors for the number boxes, border, and text. Customization supports bootstrap color names (primary, secondary, success, warning, dark, light, etc.).

2023-09-14 16:15 UTC, jedgar1mx approved these changes

2023-09-14 16:15 UTC, merged